"""add infohub date

Revision ID: da2bbaff125a
Revises: 8a304d90cb6d
Create Date: 2025-09-02 21:39:53.267842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2bbaff125a'
down_revision = '8a304d90cb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_hub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_hub', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
